---
name: Repository Dispatch
on:
  repository_dispatch:
    types: [pangeo-release]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.tag }}
      - run: echo ${{ github.event.client_payload.tag }}
