---
name: Repository Dispatch
on:
  repository_dispatch:
    types: [pangeo-release]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Find and Replace Base
        uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          include: "binder/"
          find: "FROM pangeo/base-image:*"
          replace: "FROM pangeo/base-image:${{ github.event.client_payload.tag }} " 

      - uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: "Release"
          branch: master
          file_pattern: binder/Dockerfile
          #
          # Optional commit user and author settings
          commit_user_name: My GitHub Actions Bot
          commit_user_email: my-github-actions-bot@example.org
          commit_author: Author <actions@github.com>

          # Optional tag message. Will create and push a new tag to the remote repository
          tagging_message: '${{ github.event.client_payload.tag }}'
