---
name: Repository Dispatch
on:
  repository_dispatch:
    types: [pangeo-release]
jobs:
  myEvent:
    runs-on: ubuntu-latest

    steps:
      - name: Find and Replace Base
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.tag }}
      - uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          include: "binder/"
          find: "FROM pangeo/base-image: "
          replace: "FROM pangeo/base-image:${{ github.event.client_payload.tag }} " 
